[package]
name = "bexio-to-pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
calamine = "0.19.1"
genpdf = "0.2.0"
